name: Release Workflow

on:
  push:
    tags:
      - v*

jobs:
  release-blockchain:
    name: "Publish Blockchain 📢 "
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
      - name: Prepare Release Variables
        id: vars
        uses: tendermint/starport/actions/release/vars@develop

      - name: Issue Release Assets
        uses: tendermint/starport/actions/cli@develop
        if: ${{ steps.vars.outputs.should_release == 'true' }}
        with:
          args: chain build --release --release.prefix ${{ steps.vars.outputs.tarball_prefix }} -t linux:amd64 -t darwin:amd64

      - name: Delete the "latest" Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
